export interface Country {
	code: string
	name: string
	aliases?: string[]
}

export const countries: Country[] = [
	{ code: "AF", name: "Afghanistan" },
	{ code: "ZA", name: "Afrique du Sud", aliases: ["Afrique Sud"] },
	{ code: "AL", name: "Albanie" },
	{ code: "DZ", name: "Algérie" },
	{ code: "DE", name: "Allemagne" },
	{ code: "AD", name: "Andorre" },
	{ code: "AO", name: "Angola" },
	{ code: "AG", name: "Antigua-et-Barbuda", aliases: ["Antigua"] },
	{ code: "SA", name: "Arabie Saoudite", aliases: ["Arabie"] },
	{ code: "AR", name: "Argentine" },
	{ code: "AM", name: "Arménie" },
	{ code: "AU", name: "Australie" },
	{ code: "AT", name: "Autriche" },
	{ code: "AZ", name: "Azerbaïdjan" },
	{ code: "BS", name: "Bahamas" },
	{ code: "BH", name: "Bahreïn" },
	{ code: "BD", name: "Bangladesh" },
	{ code: "BB", name: "Barbade" },
	{ code: "BE", name: "Belgique" },
	{ code: "BZ", name: "Belize" },
	{ code: "BJ", name: "Bénin" },
	{ code: "BT", name: "Bhoutan" },
	{ code: "BY", name: "Biélorussie" },
	{ code: "MM", name: "Birmanie" },
	{ code: "BO", name: "Bolivie" },
	{ code: "BA", name: "Bosnie-Herzégovine", aliases: ["Bosnie"] },
	{ code: "BW", name: "Botswana" },
	{ code: "BR", name: "Brésil" },
	{ code: "BN", name: "Brunei" },
	{ code: "BG", name: "Bulgarie" },
	{ code: "BF", name: "Burkina Faso" },
	{ code: "BI", name: "Burundi" },
	{ code: "KH", name: "Cambodge" },
	{ code: "CM", name: "Cameroun" },
	{ code: "CA", name: "Canada" },
	{ code: "CV", name: "Cap-Vert", aliases: ["Cap Vert"] },
	{ code: "CL", name: "Chili" },
	{ code: "CN", name: "Chine" },
	{ code: "CY", name: "Chypre" },
	{ code: "CO", name: "Colombie" },
	{ code: "KM", name: "Comores" },
	{ code: "CG", name: "Congo" },
	{ code: "KP", name: "Corée du Nord", aliases: ["Coree du Nord"] },
	{ code: "KR", name: "Corée du Sud", aliases: ["Coree du Sud"] },
	{ code: "CR", name: "Costa Rica" },
	{
		code: "CI",
		name: "Côte d'Ivoire",
		aliases: ["Cote d'Ivoire", "Cote Ivoire"],
	},
	{ code: "HR", name: "Croatie" },
	{ code: "CU", name: "Cuba" },
	{ code: "DK", name: "Danemark" },
	{ code: "DJ", name: "Djibouti" },
	{ code: "DM", name: "Dominique" },
	{ code: "EG", name: "Égypte" },
	{
		code: "AE",
		name: "Émirats Arabes Unis",
		aliases: ["UAE", "EAU", "Emirats"],
	},
	{ code: "EC", name: "Équateur" },
	{ code: "ER", name: "Érythrée" },
	{ code: "ES", name: "Espagne" },
	{ code: "EE", name: "Estonie" },
	{ code: "SZ", name: "Eswatini" },
	{
		code: "US",
		name: "États-Unis",
		aliases: ["USA", "US", "Etats Unis", "Amerique"],
	},
	{ code: "ET", name: "Éthiopie" },
	{ code: "FJ", name: "Fidji" },
	{ code: "FI", name: "Finlande" },
	{ code: "FR", name: "France" },
	{ code: "GA", name: "Gabon" },
	{ code: "GM", name: "Gambie" },
	{ code: "GE", name: "Géorgie" },
	{ code: "GH", name: "Ghana" },
	{ code: "GR", name: "Grèce" },
	{ code: "GD", name: "Grenade" },
	{ code: "GT", name: "Guatemala" },
	{ code: "GN", name: "Guinée" },
	{ code: "GW", name: "Guinée-Bissau", aliases: ["Guinee Bissau"] },
	{ code: "GQ", name: "Guinée Équatoriale", aliases: ["Guinee Equatoriale"] },
	{ code: "GY", name: "Guyana" },
	{ code: "HT", name: "Haïti" },
	{ code: "HN", name: "Honduras" },
	{ code: "HU", name: "Hongrie" },
	{ code: "MH", name: "Îles Marshall" },
	{ code: "SB", name: "Îles Salomon" },
	{ code: "IN", name: "Inde" },
	{ code: "ID", name: "Indonésie" },
	{ code: "IQ", name: "Irak" },
	{ code: "IR", name: "Iran" },
	{ code: "IE", name: "Irlande" },
	{ code: "IS", name: "Islande" },
	{ code: "IL", name: "Israël" },
	{ code: "IT", name: "Italie" },
	{ code: "JM", name: "Jamaïque" },
	{ code: "JP", name: "Japon" },
	{ code: "JO", name: "Jordanie" },
	{ code: "KZ", name: "Kazakhstan" },
	{ code: "KE", name: "Kenya" },
	{ code: "KG", name: "Kirghizistan" },
	{ code: "KI", name: "Kiribati" },
	{ code: "XK", name: "Kosovo" },
	{ code: "KW", name: "Koweït" },
	{ code: "LA", name: "Laos" },
	{ code: "LS", name: "Lesotho" },
	{ code: "LV", name: "Lettonie" },
	{ code: "LB", name: "Liban" },
	{ code: "LR", name: "Liberia" },
	{ code: "LY", name: "Libye" },
	{ code: "LI", name: "Liechtenstein" },
	{ code: "LT", name: "Lituanie" },
	{ code: "LU", name: "Luxembourg" },
	{ code: "MK", name: "Macédoine du Nord", aliases: ["Macedoine"] },
	{ code: "MG", name: "Madagascar" },
	{ code: "MY", name: "Malaisie" },
	{ code: "MW", name: "Malawi" },
	{ code: "MV", name: "Maldives" },
	{ code: "ML", name: "Mali" },
	{ code: "MT", name: "Malte" },
	{ code: "MA", name: "Maroc" },
	{ code: "MU", name: "Maurice" },
	{ code: "MR", name: "Mauritanie" },
	{ code: "MX", name: "Mexique" },
	{ code: "FM", name: "Micronésie" },
	{ code: "MD", name: "Moldavie" },
	{ code: "MC", name: "Monaco" },
	{ code: "MN", name: "Mongolie" },
	{ code: "ME", name: "Monténégro" },
	{ code: "MZ", name: "Mozambique" },
	{ code: "NA", name: "Namibie" },
	{ code: "NR", name: "Nauru" },
	{ code: "NP", name: "Népal" },
	{ code: "NI", name: "Nicaragua" },
	{ code: "NE", name: "Niger" },
	{ code: "NG", name: "Nigeria" },
	{ code: "NO", name: "Norvège" },
	{ code: "NZ", name: "Nouvelle-Zélande", aliases: ["Nouvelle Zelande"] },
	{ code: "OM", name: "Oman" },
	{ code: "UG", name: "Ouganda" },
	{ code: "UZ", name: "Ouzbékistan" },
	{ code: "PK", name: "Pakistan" },
	{ code: "PW", name: "Palaos" },
	{ code: "PS", name: "Palestine" },
	{ code: "PA", name: "Panama" },
	{ code: "PG", name: "Papouasie-Nouvelle-Guinée", aliases: ["Papouasie"] },
	{ code: "PY", name: "Paraguay" },
	{ code: "NL", name: "Pays-Bas" },
	{ code: "PE", name: "Pérou" },
	{ code: "PH", name: "Philippines" },
	{ code: "PL", name: "Pologne" },
	{ code: "PT", name: "Portugal" },
	{ code: "QA", name: "Qatar" },
	{
		code: "CF",
		name: "République Centrafricaine",
		aliases: ["RCA", "Centrafrique"],
	},
	{
		code: "CD",
		name: "République Démocratique du Congo",
		aliases: ["RDC", "Congo-Kinshasa"],
	},
	{ code: "DO", name: "République Dominicaine", aliases: ["Dominicaine"] },
	{
		code: "CZ",
		name: "République Tchèque",
		aliases: ["Tcheque", "Tchequie"],
	},
	{ code: "RO", name: "Roumanie" },
	{
		code: "GB",
		name: "Royaume-Uni",
		aliases: ["UK", "Angleterre", "Grande-Bretagne"],
	},
	{ code: "RU", name: "Russie" },
	{ code: "RW", name: "Rwanda" },
	{
		code: "KN",
		name: "Saint-Christophe-et-Niévès",
		aliases: ["Saint Christophe"],
	},
	{ code: "LC", name: "Sainte-Lucie", aliases: ["Sainte Lucie"] },
	{ code: "SM", name: "Saint-Marin", aliases: ["Saint Marin"] },
	{
		code: "VC",
		name: "Saint-Vincent-et-les-Grenadines",
		aliases: ["Saint Vincent"],
	},
	{ code: "WS", name: "Samoa" },
	{ code: "ST", name: "São Tomé-et-Príncipe", aliases: ["Sao Tome"] },
	{ code: "SN", name: "Sénégal" },
	{ code: "RS", name: "Serbie" },
	{ code: "SC", name: "Seychelles" },
	{ code: "SL", name: "Sierra Leone" },
	{ code: "SG", name: "Singapour" },
	{ code: "SK", name: "Slovaquie" },
	{ code: "SI", name: "Slovénie" },
	{ code: "SO", name: "Somalie" },
	{ code: "SD", name: "Soudan" },
	{ code: "SS", name: "Soudan du Sud", aliases: ["Sud Soudan"] },
	{ code: "LK", name: "Sri Lanka" },
	{ code: "SE", name: "Suède" },
	{ code: "CH", name: "Suisse" },
	{ code: "SR", name: "Suriname" },
	{ code: "SY", name: "Syrie" },
	{ code: "TJ", name: "Tadjikistan" },
	{ code: "TZ", name: "Tanzanie" },
	{ code: "TD", name: "Tchad" },
	{ code: "TH", name: "Thaïlande" },
	{ code: "TL", name: "Timor Oriental", aliases: ["Timor"] },
	{ code: "TG", name: "Togo" },
	{ code: "TO", name: "Tonga" },
	{ code: "TT", name: "Trinité-et-Tobago", aliases: ["Trinite"] },
	{ code: "TN", name: "Tunisie" },
	{ code: "TM", name: "Turkménistan" },
	{ code: "TR", name: "Turquie" },
	{ code: "TV", name: "Tuvalu" },
	{ code: "UA", name: "Ukraine" },
	{ code: "UY", name: "Uruguay" },
	{ code: "VU", name: "Vanuatu" },
	{ code: "VA", name: "Vatican" },
	{ code: "VE", name: "Venezuela" },
	{ code: "VN", name: "Viêt Nam" },
	{ code: "YE", name: "Yémen" },
	{ code: "ZM", name: "Zambie" },
	{ code: "ZW", name: "Zimbabwe" },
]

export function getRandomCountry(): Country {
	return countries[Math.floor(Math.random() * countries.length)]!
}

export function getCountryByCode(code: string): Country | undefined {
	return countries.find((c) => c.code === code)
}

export function getCountryByName(name: string): Country | undefined {
	return countries.find((c) => c.name.toLowerCase() === name.toLowerCase())
}
